version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    depends_on:
      - composer

  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
    command: install

  test:
    build:
      context: .
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ./vendor/bin/phpunit
