name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker containers
        run: docker-compose build

      - name: Install Composer dependencies
        run: docker-compose run --rm composer install --no-interaction --prefer-dist

      - name: Copy .env.example to .env
        run: docker-compose run --rm app cp .env.example .env

      - name: Generate app key
        run: docker-compose run --rm app php artisan key:generate

      - name: Run PHPUnit tests
        run: docker-compose run --rm app ./vendor/bin/phpunit --colors=always
